[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "VolleyballVisualAnalysis"
version = "0.1.0"
description = "A project for visual analysis of volleyball games."
readme = "README.md"
requires-python = ">=3.10,<3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "inference-sdk",
    "opencv-python",
    "numpy",
    "PyYAML",
    "python-dotenv",
    "pydantic>=2",
    "pydantic-settings",
    "requests",
]

[tool.setuptools.packages.find]
where = ["."]

[project.optional-dependencies]
local-yolo = [
    "ultralytics>=8.1"
]
